[build]
builder = "dockerfile"

[deploy]
startCommand = "npm start --prefix simple-backend"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3 